# Generated by Django 3.2.6 on 2021-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=700, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(blank=True, max_length=400, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
